# .streamlit/secrets.toml  (do not commit)
OWM_KEY = "bfa0b7e95565c2681810babd2d154346"
TELEGRAM_BOT_TOKEN = "8096416788:AAGWzc0Q0nF0E6H5kzDez8udCnQIdP82Jq4"
TELEGRAM_CHAT_ID = "6118844296"
MAPTILER_KEY = "XX4EIukOvXiwje5I1a3Z"
# Optional:
# DATA_GOV_SG_API_KEY = "YOUR_SG_KEY"